<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Figgle" Version="0.6.6" />
    <PackageVersion Include="Figgle.Fonts" Version="0.6.6" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
  </ItemGroup>

  <ItemGroup Label="Test">
    <PackageVersion Include="Spectre.Console.Testing" Version="0.57.2" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>
</Project>
