namespace NextIteration.SpectreConsole.Splash.Internal
{
    /// <summary>
    /// Built-in tagline pool used when
    /// <see cref="SplashTagline.RandomBuiltIn"/> is selected. Geeky
    /// developer-culture one-liners; the list is intentionally large so
    /// the same quote doesn't appear twice in a row during normal use.
    /// </summary>
    internal static class Quotes
    {
        private static readonly string[] Pool =
        [
            "Reticulating splines",
            "Have you tried turning it off and on again?",
            "sudo make me a sandwich",
            "I see dead servers",
            "There is no cloud, just someone else's computer",
            "I'm not lazy, I'm on energy-saving mode",
            "To the cloud! (aka someone else's problem)",
            "You had me at 'Hello World'",
            "I, for one, welcome our new AI overlords",
            "rm -rf / but make it fashion",
            "My other computer is also crashing",
            "Ctrl+Alt+Del: my coping mechanism",
            "Ping me maybe?",
            "Talk data to me",
            "May the source be with you",
            "Gone phishing",
            "Live, laugh, loop forever",
            "Debugging: because typing works better than crying",
            "You either die a dev, or live long enough to see yourself become QA",
            "It's not a bug, it's a feature",
            "Stack Overflow is my spirit animal",
            "99 little bugs in the code…",
            "Keep calm and clear the cache",
            "There's no place like 127.0.0.1",
            "Oops, I dropped the production database",
            "AI wrote this bug, not me",
            "Resistance is futile, updates are mandatory",
            "I am root, hear me roar",
            "Never trust a computer you can't throw out a window",
            "I found Nemo.txt",
            "Welcome to the dark mode side",
            "Oops, all meetings",
            "In Git we trust",
            "Alt+F4 for enlightenment",
            "Cache me if you can",
            "One does not simply deploy on Friday",
            "Do. Or do not. There is no try-catch.",
            "I solemnly swear I am up to no code",
            "Why so semicolon?",
            "Keep your friends close and your backups closer",
            "Latency is just time travel",
            "Never gonna give you root",
            "Oops, I JSONed my pants",
            "YAML is a four-letter word",
            "Wi-Fight for freedom",
            "Another day, another null pointer",
            "I'm silently judging your variable names",
            "Oops… prod not test",
            "Ctrl+C and Ctrl+V are my superpowers",
            "Update available: your sanity",
            "DNS is hard, let's go shopping",
            "The cake is a false positive",
            "I don't always test my code, but when I do, it's in prod",
            "When in doubt, reboot",
            "Java: write once, debug everywhere",
            "This code runs on coffee",
            "Hello from the other side (of the firewall)",
            "User error: replace user",
            "Merge conflict of interest",
            "99 problems but a Git ain't one",
            "Hack the planet!",
            "Segmentation fault: core dumped",
            "Fear is the path to the dark side, and infinite loops",
            "Data, data everywhere, not a byte to think",
            "Nerd? I prefer 'intellectual badass'",
            "Working hard, or hardly networking?",
            "My password is swordfish",
            "Oops, I tabbed instead of spaced",
            "Half my day is fixing typos",
            "Embrace the chaos monkey",
            "Cloudy with a chance of downtime",
            "I see fields of green, variables too",
            "Docker is my container of emotions",
            "Objects are closer than they appear",
            "Computers make very fast, very accurate mistakes",
            "Don't feed the trolls, patch them",
            "I ship it like FedEx",
            "My brain.exe has stopped working",
            "Zero bugs given",
            "Virtual insanity",
            "Trust me, I'm not in QA",
            "Coffee first, commit later",
            "Think outside the black box",
            "Console.WriteLine(\"Life is good\");",
            "Assembly required",
            "All your base are belong to us",
            "Insert witty error message here",
            "It compiles? Ship it!",
            "One ping to rule them all",
            "Powered by pizza and caffeine",
            "AI is just autocomplete deluxe",
            "Welcome to Jurassic Park.exe",
            "Do not disturb, updating drivers",
            "Roses are #FF0000, violets are #0000FF",
            "Infinite loop, infinite sadness",
            "Keyboard not responding, press any key",
            "Oops, recursion detected",
            "The code is strong with this one",
            "99 bugs fixed, 127 new created",
            "I dream in binary",
            "Cache rules everything around me",
            "Oops, my brain is in airplane mode",
            "Never deploy on Monday either",
            "This commit broke reality",
            "Don't cross the streams (unless debugging)",
            "Here be dragons",
            "Keep coding and carry on",
            "My cat walked across the keyboard, and now it works",
            "Hello, IT. Have you tried turning it off and on again?",
            "To boldly go where no stack trace has gone",
            "Every day I'm buffering",
            "Can't stop, refactoring",
            "Spaghetti code with extra sauce",
            "Caffeine overflow exception",
            "Waiting for Godot.exe",
            "Lag is just time dilation",
            "End of line — Tron",
            "Insert coin to continue",
            "Hackerman approves",
            "Keep calm and type faster",
            "Objects are just data with attitude",
            "My Wi-Fi spirit animal is a potato",
            "Ctrl+Z my mistakes",
            "Rage quitting IRL",
            "Kernel panic in progress",
            "My spirit animal is a rubber duck",
            "One does not simply debug legacy code",
            "Copy, paste, deploy",
            "Endless coffee loops",
            "Fear the merge conflict",
            "Infinite scroll, infinite despair",
            "May the forks be with you",
            "Bugged, not broken",
            "Powered by hope and Caffeine",
            "Lag kills dreams",
            "Wi-Fight continues",
            "Stack trace whisperer",
            "Ping pong developer life",
            "Too many bugs, too little time",
            "Debug mode: activated",
            "Null is my middle name",
            "Life needs a debugger",
            "Ctrl+S saves lives",
            "My commits are art",
            "Wi-Fight me bro",
            "Programmer by day, debugger by night",
            "Powered by bad decisions",
            "Never deploy angry",
            "Insert coin to reboot",
            "Reboot the universe",
            "Lag is my co-pilot",
            "Keyboard not found, press F1",
            "Syntax error at life",
            "Commit early, regret later",
            "Life's a loop, then you break",
            "May all your commits be green",
            "Lag is my lifestyle",
            "Trust me, it works locally",
            "Too many bugs spoil the code",
            "Keep calm and push to prod",
            "My brain runs on spaghetti",
            "rm -rf my sanity",
            "Code so bad it compiles",
            "404 fun not found",
            "Objects are like onions, they have layers",
            "I void warranties",
            "Spaghetti is for dinner, not code",
            "Ctrl+C, Ctrl+V forever",
            "Deploy long and prosper",
            "Oops, dropped a semicolon somewhere",
            "99 little features in the backlog…",
            "Debugging is like being a detective in a crime movie where you are also the murderer",
            "Artificially unintelligent",
            "Life in pixels",
            "There's no place like /home",
            "Keyboard warrior activated",
            "One does not simply write bug-free code",
            "Stack overflowed my patience",
            "I dream in semicolons",
            "Git happens",
            "Commit responsibly",
            "Real programmers count from 0",
            "Run fast, break things",
            "I'm silently judging your code style",
            "NullPointerException is my pet",
            "All your variables are belong to us",
            "In code we trust, all others must bring data",
            "If at first you don't succeed; call it version 1.0",
            "To iterate is human, to recurse divine",
            "I came, I saw, I Ctrl+C'd",
            "Your code is like a mystery wrapped in spaghetti",
            "May your code compile on the first try",
            "I have too many tabs open",
            "The cake is a lie, the bugs are real",
            "AI stole my job, but I debug its code",
            "Debugging: where the fun begins",
            "The only constant is chaos",
            "I have root access to your heart",
            "Coffee: the other compiler",
            "Powered by pizza and late nights",
            "Hello, darkness my old friend",
            "May your loops be infinite and your bugs be funny",
            "Stack traces are my love letters",
            "Eat, sleep, code, repeat",
            "Keep calm and git pull",
            "If it works, it's a feature",
            "Let's push this to production and hope",
            "My code is self-documenting, in a tragic way",
            "I speak fluent pseudocode",
            "I break things so you don't have to",
            "Life is too short for bad code",
            "Powered by memes and caffeine",
            "I write code that even my cat judges",
            "Keyboard and coffee required",
            "Lag happens",
            "Infinite loops for infinite fun",
            "Programmer by day, wizard by night",
            "rm -rf my responsibilities",
            "Keep calm and blame the intern",
            "Oops, forgot to invent a compiler",
            "I, for one, blame the cloud",
            "Code like nobody's watching",
            "Real programmers use spaces",
            "Hello World, meet disaster",
            "Debugging is my cardio",
            "Oops, pushed to master again",
            "Infinite recursion is fun",
            "If it compiles, ship it",
            "May the bugs be ever in your favor",
            "Keep calm and refactor",
            "I dream of semicolons",
            "Version 1.0: hope is eternal",
            "Programming is 10% coding, 90% debugging",
            "Code like it's 1999",
            "Don't worry, merge conflicts are just life",
            "Eat, sleep, debug, repeat",
            "Ctrl+Alt+Del your life",
            "Keep calm and restart",
            "Hello darkness my old friend.exe",
            "Powered by curiosity and caffeine",
            "Infinite bugs, infinite possibilities",
            "Oops, forgot to comment",
            "I love the smell of code in the morning",
            "Life without bugs is boring",
            "Git pull, pray, repeat",
            "Hello World is my love language",
            "rm -rf my life choices",
            "Ctrl+Z your mistakes",
            "Debugging is believing",
            "Merge conflicts make me stronger",
            "Keyboard cat approves",
            "Stack traces tell stories",
            "Coffee is my compiler",
            "Infinite loops are my friends",
            "Debugging is like detective work",
            "Programmers do it recursively",
            "I write code like a wizard casts spells",
            "I refactor, therefore I am",
            "Code is poetry in motion",
            "I make software, I break reality",
            "Powered by hope, fueled by bugs",
            "Ctrl+C, Ctrl+V, Ctrl+Sleep",
            "I write code, not excuses",
            "Life is short, code fast",
            "Keep calm and deploy",
            "I dream of clean code",
            "Git commit, git push, git nap",
            "Hello World, meet chaos",
            "Debugging is my superpower",
            "Programming is like magic with syntax",
            "Code like nobody's reviewing",
            "Stack traces are like breadcrumbs",
            "I refactor in my sleep",
            "Compile or cry trying",
            "Powered by coffee, cursed by bugs",
            "Life is a bug, fix it",
            "Code, coffee, repeat",
            "I merge, therefore I am",
            "Infinite loops are fun",
            "Hello World, goodbye sanity",
            "I code, therefore I debug",
            "Keep calm and code on",
            "Oops, infinite loop",
            "Powered by caffeine and memes",
            "I write code, I make magic",
            "Debugging is life",
            "Ctrl+Alt+Del everything",
            "Life is a stack trace",
            "Code hard, debug harder",
            "Merge conflicts are adventures",
            "Git push and hope",
            "Debugging: the art of patience",
            "rm -rf my worries",
            "Infinite recursion: my cardio",
            "Powered by code and caffeine",
            "Ctrl+C mistakes",
            "Debugging is like treasure hunting",
            "Hello World, meet bugs",
            "Code is my playground",
            "I write bugs with love",
            "Stack traces tell tales",
            "Coffee first, code later",
            "Git commit your soul",
            "Keep calm and fix the bug",
            "I dream in code",
            "Hello World, chaos begins",
            "Ctrl+Z regrets",
            "I write magic in code",
            "Infinite loops are friends",
            "Code like it's magic",
            "Powered by hope and bugs",
            "I debug, therefore I am",
            "Ctrl+Alt+Del my life"
        ];

        /// <summary>
        /// Returns a random quote. Uses <see cref="Random.Shared"/> so the
        /// call is thread-safe and cheap; no allocations.
        /// </summary>
        internal static string Random() => Pool[System.Random.Shared.Next(Pool.Length)];

        /// <summary>Total number of quotes in the pool. Exposed for tests.</summary>
        internal static int Count => Pool.Length;

        /// <summary>All quotes, as a read-only span. Exposed for tests.</summary>
        internal static ReadOnlySpan<string> All => Pool;
    }
}
